### ISSUE TITLE
function Cldr.Gettext.Plural.nplurals/1 is undefined or private

### ISSUE THREAD

**Issue by alaadahmed** [elixir-cldr/cldr#148]
I was following documentation and trying to add this `use Gettext, plural_forms: Cldr.Gettext.Plural` to my `MyApp.Gettext` module, but I got this error 
```
== Compilation error in file lib/ahram_school_web/gettext.ex ==
** (UndefinedFunctionError) function Cldr.Gettext.Plural.nplurals/1 is undefined or private
    (ex_cldr 2.22.1) Cldr.Gettext.Plural.nplurals("ar")
    (gettext 0.18.2) lib/gettext/compiler.ex:587: Gettext.Compiler.warn_if_missing_plural_forms/4
    (gettext 0.18.2) lib/gettext/compiler.ex:539: Gettext.Compiler.compile_translation/7
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (gettext 0.18.2) lib/gettext/compiler.ex:452: Gettext.Compiler.compile_po_file/4
    (gettext 0.18.2) lib/gettext/compiler.ex:407: Gettext.Compiler.compile_serial_po_file/3
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (gettext 0.18.2) expanding macro: Gettext.Compiler.__before_compile__/1
    lib/ahram_school_web/gettext.ex:1: AhramSchoolWeb.Gettext (module)
    (elixir 1.12.1) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by kipcole9** [comment]
Sorry for the inconvenience @alaadahmed. It's a documentation error which I've now fixed to read:

## Gettext Backend Pluralization Support

There is an experimental plurals module for Gettext called `MyApp.Cldr.Gettext.Plural` (where `MyApp.Cldr` is the name of your backend module). It is configured in `Gettext` by:
```elixir
    defmodule MyApp.Gettext do
      use Gettext, plural_forms: MyApp.Cldr.Gettext.Plural
    end
```

Basically, in your case, use `use Gettext, plural_forms: MyApp.Cldr.Gettext.Plural` where `MyApp.Cldr` is the name of your CLDR backend module.

Please report back if that now works for you - and of course please definitely report back if it does not!

**Comment by kipcole9** [comment]
Hmmm, seems to be more to it than that. I am investigating.

**Comment by alaadahmed** [comment]
Yes I understand that `MyApp.Cldr` is my CLDR backend, I did actually what you said but it didn't work either.

<img width="882" alt="Screen Shot 2021-06-06 at 12 46 46" src="https://user-images.githubusercontent.com/14099508/120921750-67f68c00-c6c5-11eb-8a5c-c93ca6f93012.png">

```
== Compilation error in file lib/ahram_school_web/gettext.ex ==
** (UndefinedFunctionError) function AhramSchoolWeb.Cldr.Gettext.Plural.nplurals/1 is undefined (module AhramSchoolWeb.Cldr.Gettext.Plural is not available)
    AhramSchoolWeb.Cldr.Gettext.Plural.nplurals("ar")
    (gettext 0.18.2) lib/gettext/compiler.ex:587: Gettext.Compiler.warn_if_missing_plural_forms/4
    (gettext 0.18.2) lib/gettext/compiler.ex:539: Gettext.Compiler.compile_translation/7
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (gettext 0.18.2) lib/gettext/compiler.ex:452: Gettext.Compiler.compile_po_file/4
    (gettext 0.18.2) lib/gettext/compiler.ex:407: Gettext.Compiler.compile_serial_po_file/3
    (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (gettext 0.18.2) expanding macro: Gettext.Compiler.__before_compile__/1
    lib/ahram_school_web/gettext.ex:1: AhramSchoolWeb.Gettext (module)
    (elixir 1.12.1) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by kipcole9** [comment]
Thanks for your patience. I've been digging deeper and there is a more fundamental issue I need to resolve relating to compile time dependencies.  I'm working on it now but it might take a day or so to finally resolve properly.  Will that timing be ok for you?

**Comment by kipcole9** [comment]
BTW so happy to see someone working in non-Latin scripts. Please do let me know if you see any other issues!

**Comment by alaadahmed** [comment]
I was shocked actually with the tremendous amount of efforts you put in these packages, I am the happy one here. Sure take your time, I really appreciate your time and efforts that you will spend or spent already. Thanks you and I would report any issue if I found. I read most of documentation today at the morning and it is fascinating.

**Comment by kipcole9** [comment]
Still working on this issue. In the meantime, looking at your configuration, I think it can be a bit simpler:
```elixir
defmodule AhramSchoolWeb.Cldr do
  @moduledoc """
  Define a backend module that will host our
  Cldr configuration and public API.

  Most function calls in Cldr will be calls
  to functions on this module.
  """
  use Cldr,
    # not required, get text locales are merged here anyway
    # locales: Gettext.known_locales(AhramSchoolWeb.Gettext),
    default_locale: "ar",
    providers: [Cldr.Number, Cldr.Calendar, Cldr.DateTime],
    add_fallback_locales: true,
    gettext: AhramSchoolWeb.Gettext,
    otp_app: :ahram_school,
    # Not required, this is the default 
    # data_dir: "./priv/cldr",
    # Not required, this is the default
    # generate_docs: true,
    precompile_transliterations: [{:latn, :arab}, {:arab, :latn}],
    precompile_number_formats: ["#,##0.00 ¤", "¤#,##0.00"],
    # Shouldn't be required, locales are downloaded at compile time
    # force_locale_download: Mix.env() == :prod 
end
```

**Comment by alaadahmed** [comment]
Thank you, I modified them now. This is the first time for me to use CLDR in any application, but will not be last.

**Comment by alaadahmed** [comment]
I thought also, if I removed `add_fallback_locales`, this will remove the `"root"` locale, but it doesn't!

**Comment by kipcole9** [comment]
You are right, the "root" locale is included no matter what you configure. Certain operations require data that is only stored in the "root" locale.

It's possible that I can't actually fix this issue since there is a compile time circular dependency.  `ex_cldr` needs the `Gettext` backend to be compiled before it so that it can find out what locales are configured on it.

The `Gettext` backend, when there is a custom `:plural_forms` module configured, needs that module compiled before it.

Since the `:plural_forms` module is part of `ex_cldr` we end up in a dependency loop that can't be resolved.

I have a couple more experiments to try and will see where that leads.

**Comment by alaadahmed** [comment]
Ah now I understand the reason behind that error. I hope you will reach to some solution for that.

**Comment by alaadahmed** [comment]
Is it possible to tell `ex_cldr` about what locales are configured without `Gettext`, I mean enter them manually so it will be compiled successfully, as a workaround, then `Gettext` will be also compiled because `ex_cldr` already compiled!

**Comment by kipcole9** [comment]
I think you might be right.  Here's what I'm thinking (not yet proven if it will work satisfactorily):

1. If not using a custom pluralizer, then configuration stays the same - specify the module name.
2. If using a custom pluralizer, then the configuration should be a list of valid Gettext locales. To make this easy I'll add a function `Cldr.Config.gettext_locales_from_directory/1` or some such name.

I was concerned that there are other requirements to have the Gettext module name be always known. But the only requirement is in `Cldr.Plug.SetLocale` and I can preserve the current semantics while make the change above.

I may not finish this change until the weekend. Until then, I wonder if you really do need a custom pluralizer in your Gettext backend?  Gettext's default pluralizer does a reasonable job so perhaps thats enough and you only configured a custom pluralizer because you thought one was required?

**Comment by alaadahmed** [comment]
I am not sure really, but I wanted to use it because I have the default one with Gettext doesn't convert numbers to arabic format. For example:
I have `<%= gettext("Attach up to %{count} files", count: 3) %>`. This should be translated to 2 other languages __"Arabic"__ and __"German"__. For German there is no problem, but for Arabic, numbers appear in English i.e: `1,2,3` but I thought if I used the Cldr.Plural it will be in Arabic format i.e: `١،٢،٣،٤،٥`. 
So for the mentioned example above, in __Arabic__ it should be: __"ارفق حتى ٣ ملفات"__ but what I get is: __"ارفق حتى 3 ملفات"__
So what do you think? Actually I am not in hurry and you can take your time, but it will be very convenient addition if you could manage to solve it, I am not sure!

**Comment by alaadahmed** [comment]
<img width="413" alt="Screen Shot 2021-06-07 at 23 43 33" src="https://user-images.githubusercontent.com/14099508/121091545-71c5df80-c7ea-11eb-8ec0-dcc199607173.png">

As you see, I used `Cldr.Date.to_string` to show date in `arabic` format, and this is fantastic, but when I used `ngettext` to show the reading time, numbers still appear in English.

**Comment by kipcole9** [comment]
Ah, yes, I see your point. The thing is that `Gettext` doesn't know about scripts.  So even a custom pluralizer won't help there. I see two approaches you might consider:

1. Pre-format the number before you do message formatting. For example, instead of `<%= ngettext("1 minute read", "%{count} minutes read", read_time(post.content)) %>`, do (not tested!):
```elixir
<%= ngettext("1 minute read", "%{minutes} minutes read", read_time(post.content), minutes:  Cldr.Number.to_string(read_time(post.content)) %>
``` 
which will use `ex_cldr` to format the number. If the locale is set to `ar` I think the default script is `Arab` and you should be ok.

2.  It may be that [ex_cldr_messages](https://hex.pm/packages/ex_cldr_messages) fits your needs better because it is designed for I18n and formats "everything" in a localised way. Its not a full translation library but @tmbb has been working on a very very cool library called [ex_i18n](https://github.com/tmbb/ex_i18n) that is an alternative to `Gettext` (and much better in my opinion).

**Comment by alaadahmed** [comment]
Thanks a lot, I will check that out. I think then you can close this issue if anyway `Cldr.Gettext.Plural` is experimental and not related to the issue.

**Comment by kipcole9** [comment]
I really appreciate you opening the issue. It identified a bug (and a lack of tests) that I need to fix and thats very helpful.

True that its unrelated to the original challenge you had but I hope the options above will help get you there.  I will close this now, and respond to the issue you raised on `ex_cldr_numbers` :-)

**Comment by alaadahmed** [comment]
I checked the `ex_i18n` and `cldr_message` and read their documentation, but to be honest they have poor documentation! I didn't figure out how to use them, or generate translation with `ex_i18n`, should I write that json file with my hand or there is a mix command that can generate it for me like `mix gettext --merge`. The same applies for `cldr_message` doesn't really has rich documentation like the main package `ex_cldr`.
