### ISSUE TITLE
Locale.locale_name type

### ISSUE THREAD

**Issue by alappe** [elixir-cldr/cldr#167]
`Cldr.put_locale/2` uses the `is_locale_name` guard:

```
defguard is_locale_name(locale_name) when is_atom(locale_name) or is_binary(locale_name)
```

but is typed:

```
 @spec put_locale(backend(), Locale.locale_name() | LanguageTag.t()) :: {:ok, LanguageTag.t()} | {:error, {module(), String.t()}}
```

where `Locale.locale_name` is typed:

```
@type locale_name() :: atom()
```

I'm getting an error using `put_locale/2` with binary locale names. But reading the guard, this should be valid and the typing of `locale_name` should be `@type locale_name() :: atom() | String.t()`.

**Comment by kipcole9** [comment]
Fixed in commit [e075eb081]( https://github.com/elixir-cldr/cldr/commit/e075eb081e3623c707cb6b185b24377e5e1db032) and published as [ex_cldr version 2.26.2](https://hex.pm/packages/ex_cldr/2.26.3) with the following changelog entry:

### Bug Fixes

* Fix spec of `Cldr.put_locale/2`. Thanks to @alappe for the report. Closes #167.

Thanks for the report and collaboration and apologies for the inconvenience. I've added a function to [dev/cldr_backend.ex](https://github.com/elixir-cldr/cldr/blob/master/dev/cldr_backend.ex#L11-L14) to ensure `dialyzer` can check the type in my CI.
