### ISSUE TITLE
Compiling many languages is slow

### ISSUE THREAD

**Issue by gmile** [elixir-cldr/cldr#214]
Barring the time to download the language JSON files, the following code takes around 60 seconds to compile on my computer (2018 MBP Pro, 2,2 GHz 6-Core Intel Core i7, 16Gb RAM):

```elixir
locales = ~w(
  ar hy sq az be bn bg my bs ca zh hr cs
  da nl en-GB et fo fi fr de el he hi hu
  is id it ja kk ko ku lv lt mk ms mt mr
  sr-Latn-ME nb pl pt pa ro ru sr sk sl so es
  sw sv fil ta th tr uk ur vi cy
)

Mix.install([
  {:jason, "~> 1.0"},
  {:ex_cldr, "== 2.37.2"},
])

defmodule Sample.Cldr do
  use Cldr,
    locales: locales,
    default_locale: "en-GB",
    providers: []
end
```

This was extracted from an actual application that's running in production. Compiling this currently the single slowest part of compiling the entire application (over 1000 modules).

Is there a way in principle the compilation speed could be improved here, or is compiling `Sample.Cldr` will always be inherently slow? I noticed the compilation time is smaller if the amount of languages is small. But I'm curious whether there's anything else left to do, independently of the number of languages.

**Comment by kipcole9** [comment]
@gmile, unfortunately with the current design the compile time of the ex_cldr backend is inherently slow.  There is a significant amount of compile time code generation from the CLDR locale data. The time is largely proportional to the number of locales configured as your have also seen.  In fact the slowest part is actually code generation in the erlang compiler which I think is related to the number of function clauses on a number of functions. There isn't, to my knowledge, a way to make this faster with the current design.

On the positive side, runtime performance is subjectively reasonably fast. That's the tradeoff.

Perhaps there's a way to cache the `ex_cldr` modules in CI?

**Comment by gmile** [comment]
> I think is related to the number of function clauses on a number of functions

Out of curiocity, could you elaborate on this part a little bit? What's happening during the compilation?

**Comment by LostKobrakai** [comment]
During compilation all the downloaded data is turned into functions on various modules, so at runtime nothing is looked up on blobs of data, but only by patterns on functions.

**Comment by kipcole9** [comment]
Closing as no planned since there is no obvious opportunity to improve compile performance with the current architecture.  I may, some time in the future, look at ex_cldr 3.0. At that time I will experiment with other data encapsulation strategies which might improve this.

**Comment by adamwight** [comment]
This looks like a productive direction to go in, IMHO.  My use cases are theoretical at the moment, but I would prefer to have all locales available at runtime.  For example, an application building an infographic of all alphabets known to CLDR, as in [this page](https://www.unicode.org/cldr/charts/45/by_type/core_data.alphabetic_information.index.html) .

The current approach of compiling to native functions gives a type-safe and performant runtime, but maybe there's something between this and the opposite extreme, of nonengineered loading of raw files into memory for each request.  The basic operations as I understand it are to parse the individual upstream data files and transform, to cache and maybe index data, and to make it available to clients.  Since the data is large even when only using a subset, the current approach of compile-time call optimization is great for static use cases, but to make all the data available for dynamic access it seems that a long-lived agent would be reasonable?  The runtime data store could be ETS, and configurable.

This agent approach could even live alongside the current implementation, so that data can be loaded one locale at a time (eg. cache-warming for known frequent languages), or by one CLDR module over all languages (eg. locating core data for the alphabet infographic theorized above).

**Comment by kipcole9** [comment]
> but I would prefer to have all locales available at runtime

Agreed, definitely preferable.

> The basic operations as I understand it are to parse the individual upstream data files and transform, to cache and maybe index data, and to make it available to clients

True, but not quite the complete story. If it was just data transformation, indexing and retrieval then moving the implementation to a runtime configuration would be straight forward (if time consuming). It would remove the need to "backends" which, while following the well-trodden path of `gettext` is a bit of a pain (as it is for `gettext` too).  However there are some key areas where the data is actually used to generate code. For example [number format patterns](https://unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns) generate actual Elixir compiled code.  Code is also generated for [plural rules](https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules), [rule based number formats (RBNF)](https://unicode.org/reports/tr35/tr35-numbers.html#Rule-Based_Number_Formatting), [date/time formats patterns](https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns), [transforms](https://unicode.org/reports/tr35/tr35-general.html#Transforms) and eventually [collations](https://unicode.org/reports/tr35/tr35-collation.html#Contents). This challenge is not insurmountable, but it is a more radical re-architecture of the platform and overall not one I have prioritised. 

> The runtime data store could be ETS, and configurable.

I would probably make it a `behaviour` as you suggest, with the provided implementation using [persistent-term](https://www.erlang.org/doc/apps/erts/persistent_term.html)
